DROP DATABASE IF EXISTS pydb;
DROP USER IF EXISTS pyuser;


CREATE ROLE pyuser WITH LOGIN ENCRYPTED PASSWORD 'password';

CREATE DATABASE pydb OWNER pyuser;
GRANT ALL PRIVILEGES ON DATABASE pydb TO pyuser;
